### ISSUE TITLE
Use promise.all to implement sequence method

### ISSUE THREAD

**Issue by murmur76** [sgkim126/sfuture.ts#1]
Currently, it seems that `future.sequence` computes futures synchronously. So i think it would be better to use `promise.all` method but it seems that mpromise library's implementation of `promise.all` has weird behavior as it' not a static method. How do you think about that?

**Comment by sgkim126** [comment]
Sorry, I don't got what you mean synchronously.
Currently sequence uses flatMap and flatMap makes job work concurrently. So the current implementation works concurrently too.

**Comment by murmur76** [comment]
sorry, I used wrong word.
I mean current implementation of `Future.sequence` computes futures sequentially(not synchronously!) but Scala's `sequence` computes futures in parallel. So I think the easiest way to implement it is to use `Promise.all`.

**Comment by sgkim126** [comment]
You cannot computes parallel in JavaScript. Promise.all doesn't work parallel.
The only difference of Promise.all and sfuture.sequence is just the order of setting element of result array, and it is not major factor of performance.
