### ISSUE TITLE
Recover with a future

### ISSUE THREAD

**Issue by hatashiro** [sgkim126/sfuture.ts#6]
Is there any way to return a futured object in recover? I'd like to do like below:

``` js
future
  .map(...)
  .recover(function (e) {
    if (e.code === 'SOMECODE') {
      return futuredObj;
    } else {
      throw e;
    }
  });
```

It would be nice to implement something like `flatRecover`, but I'm not sure how Scala handles this.

**Comment by sgkim126** [comment]
sfuture already has it.
The name of it is [recoverWith](https://github.com/sgkim126/sfuture/blob/master/test/recoverWith.ts).

**Comment by sgkim126** [comment]
I'm sorry about lack of documentation. I'll add the description asap.

**Comment by hatashiro** [comment]
No worries. Thanks!
